### PR TITLE
Sync lightsabers branch with master

### PR DESCRIPTION
**Pull request by Setnour6**
**Note:** This does NOT update the master branch.
### What is being fixed or optimized? Is there an associated issue?
The lightsaber changes have not been implemented officially, but this current issue is about the lightsabers branch not being synced to 1.4.4, where it can be merged with the master branch. 
This PR resolves that issue by syncing changes from the master branch (1.4.4) to the lightsabers branch (1.4.3.6) and updating methods via tModPorter to allow it to work with the new changes presented through the master branch.
### What are the implementation specifics of this change? Are there any consequences?
I fixed a couple of errors (see #386 for a list of files to focus on with porting changes) and made sure that the new values match with the old values so nothing too significant changes.
There are consequences, unfortunately; bugs and issue with the lightsabers have appeared.
> the white lightsaber's right click attack not working after right -> left -> right clicks to attack, and the purple lightsaber's lightning does not appear at all.
The phaseblades all emit the same blade lighting on attack, blue-tinted and no abilities from them.

**Before merge (if it might happen)**: Please review the code files of focus on issue 386 to make changes on the forked repository under my name. Please let me know if you want the files of focus listed here as well.
Link to forked repository: https://github.com/Setnour6/StarlightRiver/tree/lightsabers

### CODE REVIEW

**Comment by ScalarVector1** [comment]
I'm not reviewing 1000+ changed files. Have this target the correct branch.

**Comment by Setnour6** [comment]
> I'm not reviewing 1000+ changed files. Have this target the correct branch.

The lightsabers branch is the only branch to be targeted in this case, given that the changes directly involve updating the lightsabers branch itself. I could make a new branch that is based on master and apply the changes there, but that will have to wait for now.

**Comment by ScalarVector1** [comment]
> 

You should be able to rebase the branch

**Comment by Setnour6** [comment]
Closed in favor of #389. Having it rebased and target master branch instead, even though I wanted the lightsabers branch itself to change and then make a seperate PR to merge the updated lightsabers branch to master

**Pull request closed without merging**
