### PR TITLE
Ceiros multiplayer

### PR DESCRIPTION
**Pull request by TripleFate**
### What is being fixed or optimized? Is there an associated issue?
This is to fix multiplayer compatibility for the items in the demo. Associated issue is that multiplayer had desyncs on basically every item.

### What are the implementation specifics of this change? Are there any consequences?
Attempted to keep functionality unchanged for all the items modified. Scraphook in particular had to be gutted and reworked to be multiplayer compatible with how fast the projectiles and events are, so that one might be slightly different now.

### CODE REVIEW

**Comment by ScalarVector1** [comment]
A number of your changes dont properly follow the style guide (https://github.com/ProjectStarlight/StarlightRiver/blob/master/STYLE_GUIDE.md), notibly there are inconsistencies in your indentation in some files 
(https://github.com/ProjectStarlight/StarlightRiver/pull/129/commits/c6b930554fa640bb93f6f538ba5676c664f1d7bb has some notible issues with this) and inlined conditionals (single-line conditionals should not have brackets, only a newline and tab)

Please review the changed files and ensure all of your formatting matches the style guide

**Comment by TripleFate** [comment]
Added another commit for styling

**Comment by ScalarVector1** [comment]
Styling looks good now, hate to be pedantic about those types of things but its important with the size of the project that everything remains consistent there. Just a final double check to make sure everything has been tested and if any outstanding issues exist? Also, you mentioned the scrapshot's functionality has changed, coudl you describe what is different about it?

**Comment by TripleFate** [comment]
no worries about the styling I didn't read the guide before now.

Scrapshot now has item.shoot = 0. which may make it not recognizable as a gun to mods like weaponholdout. This was so that It could use the UseItem function which runs on all clients instead of the Shoot function which is client only.

the gameplay change for this is that when shooting the gun it rotates towards mouse cursor always during the use animation instead of how it used to lock to where you initially click for those 30 frames.

moonstone armor still needs to have its progress visibly synced between clients.

**Comment by TripleFate** [comment]
Oh for outstanding issues I've only fixed multiplayer compatibility for the items mentioned in the commits. 

so, poltergeist armor set, breacher armor set, moonstone armor set + datsuezi, golden guillotine, scrapshot, thunderbuss, buzzsaw, twisted greatsword, flare breacher. 

still working through the remaining items from the demo

**Comment by ScalarVector1** [comment]
Alright, the gameplay changes to the scrapshot should be fine. I'll wait to merge this for the further commits for the remaining items and the boss so that everything related to multiplayer can stay in one place? Feel free to mention me either here or on discord if something comes up.

**Comment by TripleFate** [comment]
This is ready for review. 

includes multiplayer compatibility for the following items: poltergeist armor set, breacher armor set, moonstone armor set + datsuezi, vitric armor set, golden guillotine, scrapshot, thunderbuss, buzzsaw, twisted greatsword, flare breacher, ripshatter , vitric hamaxe, templeLensUpgrade, needler, vitric boss bow, bossSpear, reactive plating, ironheart, refractive blade, barbed knife, shuriken, starwood charm, glass arrowhead, band of endurance.

The vitric bow does not have projectile scale synced in multiplayer, but otherwise has no desync. I don't recommend syncing this either since it would likely require a global projectile and a packet for every single new projectile whether or not its been fired from the bow due to needing the projectile to be received prior to changing its scale.

Barrier values are now synced.

Barrier visuals are synced (please test performance hit on this since it is a whole extra call on drawplayer for every client, may want to have a setting for this)

barrier dyes can now be right clicked into the barrier slot, and shift clicked to remove them from the slot.

moving platforms now have the momentum loss similar to vanilla platforms when you drop through them.

Cieros boss battle is synced.

The "pain" effect where cieros recoils is dropped for MP since its unknown which player does a hit and that code is only ran locally. We could potentially put a packet for syncing the fancier onhit that is used a lot instead of a bespoke implementation like I did, but I was worried about this meaning there's 2 packets for every single hit for the vanilla one + custom one.

I'm unable to test the performance with a high latency setup so these changes are only tested for low latency ideal scenarios + frameskip.

**Comment by TripleFate** [comment]
I changed the onhit effects to use a shared packet instead based on our discussion. compared to previously its a little more netcode now but if we have lots of fancy onhit accessories / armors on at once it will ultimately be less

**Comment by ScalarVector1** [comment]
Looks great! Thanks a ton for adding multiplayer documentation to the StarlightPlayer/StarlightNPC Events also. Minor outstanding issue is some of the serializable modules might want to be ported to NetEasy packets in the future or vice versa but for now i'll merge this, this is something larger that will need a decision later (mostly hinging on if NetEasy has a 1.4 port whenever that comes around).

**Review by ScalarVector1 — APPROVED** [review]
Looks great! Thanks a ton for adding multiplayer documentation to the StarlightPlayer/StarlightNPC Events also. Minor outstanding issue is some of the serializable modules might want to be ported to NetEasy packets in the future or vice versa but for now i'll merge this, this is something larger that will need a decision later (mostly hinging on if NetEasy has a 1.4 port whenever that comes around).

**Pull request merged**
