### PR TITLE
Fix moving platforms being debuffable

### PR DESCRIPTION
**Pull request by ScalarVector1**
Fix for https://github.com/ProjectStarlight/StarlightRiver/issues/166 which should add full debuff immunity to moving platforms

### CODE REVIEW

**Review by SkippZzMods — APPROVED** [review]
Looks good, though inconsistent naming in the variables should probably be fixed

**Comment by ScalarVector1** [comment]
Could you elaborate on what is inconsistently named?

**Comment by SkippZzMods** [comment]
Vector2 prevPos;

public bool beingStoodOn;

public bool DontCollide = false;

also don't see the point in setting the bool to false here since thats the default value, but maybe its good for clarification idk

**Comment by ScalarVector1** [comment]
correcte

**Comment by ScalarVector1** [comment]
corrected*

**Pull request merged**
